## 框架的核心配置项和菜单结构。 业务项目需在 application-data.yml 中进行配置。
data:
  # 数据字典默认配置

  # 菜单配置
  menus:
    - id: sys
      name: 设置
      seq: 10000 # 系统管理排在后面
      icon: SettingOutlined
      children:
        - id: group_user
          name: 用户管理
          type: group
          children:
            - id: sysUser
              name: 用户管理
              path: /system/user
              icon: UserOutlined
              perm-names: [ 列表,保存,删除,重置密码,授权数据 ]
              perm-codes: [ sysUser:view,sysUser:save,sysUser:delete,sysUser:resetPwd,sysUser:grantPerm ]
            - id: sysOrg
              name: 机构管理
              path: /system/org
              icon: ApartmentOutlined
              perm-names: [ 保存 ,查看,删除 ]
              perm-codes: [ sysOrg:save,sysOrg:view,sysOrg:delete ]
            - id: sysRole
              name: 角色管理
              path: /system/role
              icon: IdcardOutlined
              perm-names: [ 管理 ]
              perm-codes: [ sysRole:manage ]
        - id: group_sys
          name: 系统设置
          type: group
          children:
            - id: sysManual
              name: 操作手册
              path: /system/sysManual
              icon: CopyOutlined
              perm-names: [ 查看,删除,保存 ]
              perm-codes: [ sysManual:view,sysManual:delete,sysManual:save ]
            - id: sysDict
              name: 数据字典
              path: /system/dict
              icon: FileSearchOutlined
              perm-names: [ 查看,保存,删除 ]
              perm-codes: [ sysDict:view,sysDict:save,sysDict:delete ]
            - id: job
              name: 作业管理
              path: /system/job
              icon: OrderedListOutlined
              perm-names: [ 查看,保存,执行一次,清理日志 ]
              perm-codes: [ job:view,job:save, job:triggerJob,job:jobLogClean ]
            - id: sysLog
              name: 操作日志
              path: /system/log
              icon: FileSearchOutlined
              perm-names: [ 查看 ]
              perm-codes: [ sysLog:view ]
            - id: sysFile
              name: 文件列表
              path: /system/file
              icon: FolderOpenOutlined
              perm-names: [ 查看,删除 ]
              perm-codes: [ sysFile:view,sysFile:delete ]
            - id: api
              name: 接口管理
              icon: ApiOutlined
              path: /system/api
              perm-names: [ 管理 ]
              perm-codes: [ api ]
  dicts:
    - name: 机构类型
      code: orgType
      group-name: 系统管理
      items:
        - name: 单位
          code: 10
          color: success
        - name: 部门
          code: 20
    - name: 审核状态
      code: approveStatus
      group-name: 系统管理
      items:
          - name: 待提交
            code: DRAFT
            color: default
          - name: 审核中
            code: PENDING
            color: warning
          - name: 审核通过
            code: APPROVED
            color: success
          - name: 审核未通过
            code: REJECTED
            color: error
    - name: 性别
      code: sex
      items:
        - name: 男
          code: MALE
        - name: 女
          code: FEMALE
        - name: 保密
          code: UNKNOWN

    - name: 是否
      code: yesNo
      items:
        - name: 是
          code: Y
          color: success
        - name: 否
          code: N
          color: error
    - name: 数据权限
      code: dataPermType
      group-name: 系统管理
      items:
        - name: 所有
          code: ALL
        - name: 本级
          code: LEVEL
        - name: 本级和子级
          code: CHILDREN
        - name: 自定义
          code: CUSTOM
    - name: 状态颜色
      code: statusColor
      items:
        - name: 成功
          code: SUCCESS
        - name: 处理中
          code: PROCESSING
        - name: 错误
          code: ERROR
        - name: 警告
          code: WARNING
        - name: 默认
          code: DEFAULT
        - name: 红色
          code: RED
        - name: 蓝色
          code: BLUE
        - name: 绿色
          code: GREEN
        - name: 灰色
          code: GRAY






