spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db_ip}:${db_port}/${db_database}?allowPublicKeyRetrieval=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&nullCatalogMeansCurrent=true
    username: ${db_username}
    password: ${db_password}

  jpa:
    hibernate.ddl-auto: update
  data:
    web:
      pageable:
        one-indexed-parameters: true
  cache:
    type: simple
logging:
  file:
    name: /data/logs/info.log
    path: /data/logs/

