data:
  menus:
    - id: sys
      children:
        - id: flowableMgr
          name: 流程引擎
          icon: BranchesOutlined
          seq: 100
          children:
            - id: flowableModel
              name: 模型管理
              path: /flowable

            - id: flowableMonitor
              name: 流程监控
              path: /flowable/monitor

    - name: 我的任务
      id: flowableTask
      path: /flowable/task
      seq: -1
      refresh-on-tab-click: true
      perms:
        - perm: flowableTask
          name: 任务管理

