db_ip: 127.0.0.1
db_port: 3306
db_database: admin-db
db_username: root
db_password: 123456
spring:
  profiles:
    active: default
  application:
    name: admin-framework


logging:
  file:
    path: ./logs
  level:
    io.admin: debug
sys:
  reset-admin-pwd: admin_framework_123456
  captcha: false
  print-exception: true
  default-password: admin_framework_123456

